### ISSUE TITLE
PyPi release?

### ISSUE THREAD

**Issue by miohtama** [cakemanny/fastclasses-json#2]
I came across this nice library from dataclasses-json issue tracker 

https://github.com/lidatong/dataclasses-json/issues/228

Are you currently planning a release (on PyPi)? Is the library still under active development?

**Comment by cakemanny** [comment]
Hey, yes, that's definitely something on my mind. I've been mulling over
recently what state it should be in to call an initial version. Hopefully
in the course of the next month

**Comment by cakemanny** [comment]
I've now put a pre-alpha version on PyPI:
https://pypi.org/project/fastclasses-json/

**Comment by miohtama** [comment]
Thank you so much Cakemanny!
