### ISSUE TITLE
Add support for encode/decode using a different name

### ISSUE THREAD

**Issue by Borealin** [cakemanny/fastclasses-json#4]
I'm using fastclasses-json to replace dataclasses-json in my project, but I encounted a tricky problem, the json I need to load contains several keywords like 'from' 'in', I need to use an alter name in field naming.
The package dataclasses-json has support this [feature](https://github.com/lidatong/dataclasses-json#encode-or-decode-using-a-different-name), but it's too slow to run. If it's hard to add support for this feature?

**Comment by cakemanny** [comment]
Hey @Borealin , 
I've added the feature, now see https://github.com/cakemanny/fastclasses-json#configuration for how to configure
Included in [v0.2.0](https://pypi.org/project/fastclasses-json/0.2.0/).
Let me know if you find any bugs

**Comment by Borealin** [comment]
@cakemanny Thank you so much, the added decoder also help fixes the decode of Union
