### ISSUE TITLE
Plan for supporting python 3.7?

### ISSUE THREAD

**Issue by louistang5** [cakemanny/fastclasses-json#6]
I did some initial testing on this library versus dataclasses-json, fastclasses-json is 15x faster.

But too bad I cannot adopt it right away, as this library only support python 3.8 or above. 

Do we have any plan to support python 3.7?

**Comment by cakemanny** [comment]
Hi Shuai,

We're making extensive use of [`typing.get_origin`](https://docs.python.org/3/library/typing.html#typing.get_origin) and [`typing.get_args`](https://docs.python.org/3/library/typing.html#typing.get_args) in this library which were only added in python 3.8

To support python 3.7 would require writing backfill implementations. I can have a look into it, especially if others are also interested.

Just out of curiosity, what's blocking you from upgrading from 3.7 to 3.8 ?

**Comment by cakemanny** [comment]
Upon further investigation, I've found that another blocker is the extensive use of [the walrus operator](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions) (`:=`)

I'm using it quite a bit in code generation to avoid double evaluation of expressions. e.g.
https://github.com/cakemanny/fastclasses-json/blob/6d8173e3de97760678fd134600b3637392d2139c/fastclasses_json/core.py#L376

To remove all uses of `:=` would require quite a lot of work.

**Comment by q0w** [comment]
@cakemanny you can use `typing-extensions` for python <3.8

**Comment by louistang5** [comment]
@cakemanny The project I'm working on is not trivial and the decision to upgrade python version is beyond something I can control. But the extensive use of `dataclasses-json` library has hurt us badly as we do serialization and deserialization a lot. That's why I'm looking for other alternatives to address that issue.

The good news is that I used a back-port compatibility library to replace all the `get_origin` and `get_args` functions (I used the `typing-utils`, but looks like `typing-extensions` is better supported and a safer choice. Thanks @q0w ). That way I was able to run the code in python 3.7 without any problem. I think it's because we don't use the certain data types in our DataClass that hit the branches where walrus operator are used. But I do think we need to address the walrus operator problem, if we don't want any surprises in the future.

**Comment by louistang5** [comment]
@cakemanny  Can you explain a bit more on the purposes of variable `t0` here? https://github.com/cakemanny/fastclasses-json/blob/master/fastclasses_json/core.py#L424-L431

Below is the print out of the generated source code using above lines. Seems like it is only locally referenced within the function `f`.
```python
debug - source code from_dict_src generated:
def from_dict(cls, o, *, infer_missing):
    args = {}
    value = o.get('test_datetime_filed')
    if value is not None:
        value = datetime.fromisoformat(__0[:-1]+"+00:00" if (__0:=value)[-1]=="Z" else __0)
    args['test_datetime_filed'] = value
    value = o.get('script_content')
    if value is not None:
        value = [ScriptEntryFast._fastclasses_json_from_dict(__0) for __0 in value]
    args['script_content'] = value
    args['language'] = o.get('language')
    return cls(**args)
```


I have tried to replace the walrus operator by removing t0 completely:
(also manually forced `HAS_DATEUTIL = False`)
```python
            def f(expr):
                if HAS_DATEUTIL and issubclass_safe(datetime, t):
                    return f'dateutil.parser.isoparse({expr})'
                else:
                    return (f'{t.__name__}.fromisoformat('
                            f'{expr}[:-1]+"+00:00" if {expr}[-1]=="Z" '
                            f'else {expr}'
                            ')')
```
Both serializing and deserializing works fine. Am I missing anything?

**Comment by cakemanny** [comment]
It's for the cases where the types are more complex and so the access expressions are not simple variable references.
Maybe it's not strictly necessary here, but there's a principle behind it.

But let's take a basic example
```python
    @dataclass
    class A:
        x: Tuple[int, datetime]
```
the code generated:
```python
def from_dict(cls, o, *, infer_missing):
    args = {}
    value = o.get('x')
    if value is not None:
        value = (__0:=(value),(__0[0],datetime.fromisoformat(__1[:-1]+"+00:00" if (__1:=__0[1])[-1]=="Z" else __1),))[1]
    args['x'] = value
    return cls(**args)
```
and a diff to the code that your change would produce
```diff
--- x	2022-03-28 23:13:47.000000000 +0200
+++ y	2022-03-28 23:14:08.000000000 +0200
@@ -2,6 +2,6 @@
     args = {}
     value = o.get('x')
     if value is not None:
-        value = (__0:=(value),(__0[0],datetime.fromisoformat(__1[:-1]+"+00:00" if (__1:=__0[1])[-1]=="Z" else __1),))[1]
+        value = (__0:=(value),(__0[0],datetime.fromisoformat((__0[1])[:-1]+"+00:00" if (__0[1])[-1]=="Z" else (__0[1])),))[1]
     args['x'] = value
     return cls(**args)
```

The access expression is `__0[1]` in this case. Indexing into a list or tuple.
Without the use of the temporary, this expression gets repeated 3 times in total, and evaluated twice.
`__0[1]` isn't that expensive, but perhaps in combination with some other features maybe you could imagine the expressions getting more complex, and if you imagine large volumes of data, it all adds up.

I think the places where we do this for `Tuple` and for `Optional` are probably more important. But hopefully that explains the priniciple.

**Comment by louistang5** [comment]
So basically explicitly using `{expr}` instead of assigning it to a new variable `t0` would still work, it's just slower. Correct? 

BTW, I ran a few tests with our DataClass, I barely notice any difference in deserialization time.

**Comment by cakemanny** [comment]
In the complex cases, yes. In the simple cases using `{expr}` directly in each place would be faster since there are fewer operations. But to distinguish those two cases adds complexity to the code and as you've said, you don't notice the difference.

Anyway. Please install v0.5.0 <https://pypi.org/project/fastclasses-json/0.5.0/> and let me know if you have any issues

**Comment by cakemanny** [comment]
So, I'm going to mark this as closed in https://github.com/cakemanny/fastclasses-json/releases/tag/v0.5.0 

Please open any new issues if you find any :)

**Comment by louistang5** [comment]
Thanks for the quick fix! @cakemanny
